### ISSUE TITLE
[NEKO] Reset connected to nonexistent wire

### ISSUE THREAD

**Issue by d1duarte** [VerticalResearchGroup/miaow#4]
In the compute_unit_fpga.v file the reset input in modules vgpr (line 335), simd (line 1004) and simf (line 1058) are connected to the nonexistent wire "rst". The correct wire is "rst_signal".
This bug is preventing vector instructions from running.

**Comment by d1duarte** [comment]
Missed the vgpr one i think

**Comment by zwabbit** [comment]
Should be fixed now.
